# Generated by Django 2.2 on 2019-05-28 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
