# Generated by Django 2.2 on 2019-05-28 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_progress_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='age',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(130)]),
        ),
        migrations.AddField(
            model_name='progress',
            name='height',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
            preserve_default=False,
        ),
    ]
